# Generated by Django 3.2 on 2021-04-10 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steppenwolf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='remark',
            new_name='version',
        ),
    ]
